# Generated by Django 3.1 on 2020-08-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_taskmodel_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
